server:
  port: 7777

spring:
  application:
    name: block-chain-zuul

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 2KB
      max-request-size: 215MB

  rabbitmq:
    addresses: 172.16.39.61:5672,172.16.39.62:5672
    username: blockchain
    password: blockchain
    virtual-host: blockchain

  sleuth:
    sampler:
      probability: 1

zuul:
  routes:
    auth-server:
      path: /auth/**
      serviceId: block-chain-security
    api-a:
      path: /sys/**
      serviceId: security-user
  ignored-services: "*"
  sensitive-headers:

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:hb56@octopus-eureka.eureka:8761/eureka/
  instance:
    status-page-url: http://172.16.40.198:32177/swagger-ui.html

swagger:
  enabled: true

ribbon:
  ReadTimeout: 24000
  ConnectTimeout: 100

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

security:
  oauth2:
    client:
      client-id: esb
      client-secret: secret
      user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
      access-token-uri: ${auth-server}/oauth/token
    resource:
      user-info-uri: ${auth-server}/user
      prefer-token-info: false
      token-info-uri: ${auth-server}/oauth/check_token
security-config:
   permit: /favicon.ico,/out,${zuul.routes.auth-server.path}
   revoke-token-uri: ${auth-server}/logout

auth-server2: http://${zuul.routes.auth-server.serviceId}
zuul-auth: http://${spring.cloud.client.ip-address}:${server.port}${zuul.routes.auth-server.path}
auth-server: http://172.16.40.198:32189

#proxy:
#  auth:
#    load-balanced: true